Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Odev.Model;
using MVC_Odev.Repository;

namespace MVC_Odev.Controllers
{
    public class AdminController : Controller
    {
        private readonly KullaniciDbContext _dbSet;

        public AdminController(KullaniciDbContext dbSet)
        {
            _dbSet = dbSet;
        }

        public IActionResult Index()
        {
            IEnumerable<Admin> objAdminList = _dbSet.Admin;
            return View(objAdminList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Admin obj)
        {
            if (ModelState.IsValid)
            {
                _dbSet.Admin.Add(obj);
                _dbSet.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var adminFromDb = _dbSet.Admin.Find(id);


            if (adminFromDb == null)
            {
                return NotFound();
            }

            return View(adminFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Admin obj)
        {

            if (ModelState.IsValid)
            {

                _dbSet.Admin.Update(obj);
                _dbSet.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var adminFromDb = _dbSet.Admin.Find(id);
            if (adminFromDb == null)
            {
                return NotFound();
            }
            return View(adminFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _dbSet.Admin.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dbSet.Admin.Remove(obj);
            _dbSet.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Odev.Models;
using System.Diagnostics;

namespace MVC_Odev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/KullaniciController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Odev.Model;
using MVC_Odev.Repository;

namespace MVC_Odev.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly KullaniciDbContext _dbSet;

        public KullaniciController(KullaniciDbContext dbSet)
        {
            _dbSet = dbSet;
        }

        public IActionResult Index()
        {
            IEnumerable<Kullanici> objKullaniciList = _dbSet.Kullanici;
            return View(objKullaniciList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Kullanici obj)
        {
            if (ModelState.IsValid)
            {
                _dbSet.Kullanici.Add(obj);
                _dbSet.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var kullaniciFromDb = _dbSet.Kullanici.Find(id);


            if (kullaniciFromDb == null)
            {
                return NotFound();
            }

            return View(kullaniciFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Kullanici obj)
        {

            if (ModelState.IsValid)
            {

                _dbSet.Kullanici.Update(obj);
                _dbSet.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var kullaniciFromDb = _dbSet.Kullanici.Find(id);
            if (kullaniciFromDb == null)
            {
                return NotFound();
            }
            return View(kullaniciFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _dbSet.Kullanici.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dbSet.Kullanici.Remove(obj);
            _dbSet.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}


Controllers/WordController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Odev.Model;
using MVC_Odev.Repository;

namespace MVC_Odev.Controllers
{
    public class WordController : Controller
    {
        private readonly KullaniciDbContext _dbSet;

        public WordController(KullaniciDbContext dbSet)
        {
            _dbSet = dbSet;
        }

        public IActionResult Index()
        {
            IEnumerable<Word> objWordList = _dbSet.Word;
            return View(objWordList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Word obj)
        {
            if (ModelState.IsValid)
            {
                _dbSet.Word.Add(obj);
                _dbSet.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var wordFromDb = _dbSet.Word.Find(id);


            if (wordFromDb == null)
            {
                return NotFound();
            }

            return View(wordFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Word obj)
        {

            if (ModelState.IsValid)
            {

                _dbSet.Word.Update(obj);
                _dbSet.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var wordFromDb = _dbSet.Word.Find(id);
            if (wordFromDb == null)
            {
                return NotFound();
            }
            return View(wordFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _dbSet.Word.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dbSet.Word.Remove(obj);
            _dbSet.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Views/Admin/Create.cshtml
@model  Admin

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Admin Ekle</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Admin Adı</label>
            <input asp-for="AdminName" class="form-control" />
            <span asp-validation-for="AdminName" class="text-danger"></span>
            <label>Admin Eposta</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Oluştur</button>
        <a asp-controller="Admin" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Admin/Delete.cshtml
@model Admin

<form method="post" asp-action="Delete">
    <input asp-for="AdminId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Admin Sil</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Admin Adı</label>
            <input asp-for="AdminName" disabled class="form-control" />
            <span asp-validation-for="AdminName" class="text-danger"></span>
            <label>Admin Eposta</label>
            <input asp-for="Email" disabled class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
           
        </div>
        <button type="submit" class="btn btn-primary">Sil</button>
        <a asp-controller="Admin" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Admin/Edit.cshtml
@model Admin

<form method="post" asp-action="Edit">
    <input asp-for="AdminId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Admin Bilgisi Güncelle</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Admin Adı</label>
            <input asp-for="AdminName" class="form-control" />
            <span asp-validation-for="AdminName" class="text-danger"></span>
            <label>Admin Eposta</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
           
        </div>
        <button type="submit" class="btn btn-primary">Güncelle</button>
        <a asp-controller="Admin" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Admin/Index.cshtml
@model IEnumerable<Admin>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="col-6">
                Admin Listesi
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Admin" asp-action="Create" class="btn btn-primary">Ekle</a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Admin Adı
            </th>
            <th>
                Admin Eposta
            </th>
           
            
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.AdminName
                </td>
                <td>
                    @obj.Email
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Admin" asp-action="Edit" asp-route-id="@obj.AdminId" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Güncelle</a>
                    </div>
                </td>
                    <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Admin" asp-action="Delete" asp-route-id="@obj.AdminId" class="btn btn-danger mx-2"><i class="bi bi-trash3"></i>Sil</a>
                        </div>
                    </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Kullanici/Create.cshtml
@model Kullanici

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kullanıcı Oluştur</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Kullanıcı Adı</label>
            <input asp-for="Ad" class="form-control" />
            <span asp-validation-for="Ad" class="text-danger"></span>
            <label>Kullanıcı Soyadı</label>
            <input asp-for="Soyad" class="form-control" />
            <span asp-validation-for="Soyad" class="text-danger"></span>
            <label>Kullanıcı Eposta</label>
            <input asp-for="Eposta" class="form-control" />
            <span asp-validation-for="Eposta" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Oluştur</button>
        <a asp-controller="Kullanici" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Kullanici/Delete.cshtml
@model Kullanici

<form method="post" asp-action="Delete">
    <input asp-for="KullaniciId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kullanıcı Sil</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Kullanıcı Adı</label>
            <input asp-for="Ad" disabled class="form-control" />
            <span asp-validation-for="sarkiAd" class="text-danger"></span>
            <label>Kullanıcı Soyad</label>
            <input asp-for="Soyad" disabled class="form-control" />
            <span asp-validation-for="Soyad" class="text-danger"></span>
            <label>Kullanıcı Eposta</label>
            <input asp-for="Eposta" disabled class="form-control" />
            <span asp-validation-for="Eposta" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Sil</button>
        <a asp-controller="Kullanici" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Kullanici/Edit.cshtml
@model Kullanici

<form method="post" asp-action="Edit">
    <input asp-for="KullaniciId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kullanıcı Bilgilerini Güncelle</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Kullanıcı Adı</label>
            <input asp-for="Ad" class="form-control" />
            <span asp-validation-for="Ad" class="text-danger"></span>
            <label>Kullanıcı Soyad</label>
            <input asp-for="Soyad" class="form-control" />
            <span asp-validation-for="Soyad" class="text-danger"></span>
            <label>Kullanıcı Eposta</label>
            <input asp-for="Eposta" class="form-control" />
            <span asp-validation-for="Eposta" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Güncelle</button>
        <a asp-controller="Kullanici" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Kullanici/Index.cshtml
@model IEnumerable<Kullanici>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="col-6">
                Kullanıcı Listesi
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Kullanici" asp-action="Create" class="btn btn-primary">Ekle</a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Kullanıcı Adı
            </th>
            <th>
                Kullanıcı Soyadı
            </th>
            <th>
                Kullanıcı Eposta
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.Ad
                </td>
                <td>
                    @obj.Soyad
                </td>
                <td>
                    @obj.Eposta
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Kullanici" asp-action="Edit" asp-route-id="@obj.KullaniciId" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Güncelle</a>
                    </div>
                </td>
                    <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Kullanici" asp-action="Delete" asp-route-id="@obj.KullaniciId" class="btn btn-danger mx-2"><i class="bi bi-trash3"></i>Sil</a>
                        </div>
                    </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ÖDEV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ÖDEV.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ÖDEV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ÖDEV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Word/Create.cshtml
@model Word

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Word Oluştur</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Word</label>
            <input asp-for="Wordname" class="form-control" />
            <span asp-validation-for="Wordname" class="text-danger"></span>
            <label>Word Title</label>
            <input asp-for="WordTitle" class="form-control" />
            <span asp-validation-for="WorTitle" class="text-danger"></span>
           
        </div>
        <button type="submit" class="btn btn-primary">Oluştur</button>
        <a asp-controller="Word" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Word/Delete.cshtml
@model Word

<form method="post" asp-action="Delete">
    <input asp-for="WordId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kelime Sil</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Word</label>
            <input asp-for="Wordname" class="form-control" />
            <span asp-validation-for="Wordname" class="text-danger"></span>
            <label>Word Title</label>
            <input asp-for="WordTitle" class="form-control" />
            <span asp-validation-for="WorTitle" class="text-danger"></span>


        </div>
        <button type="submit" class="btn btn-primary">Sil</button>
        <a asp-controller="Word" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Word/Edit.cshtml
@model Word

<form method="post" asp-action="Edit">
    <input asp-for="WorId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Kelime Güncelle</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Word</label>
            <input asp-for="Wordname" class="form-control" />
            <span asp-validation-for="Wordname" class="text-danger"></span>
            <label>Word Title</label>
            <input asp-for="WordTitle" class="form-control" />
            <span asp-validation-for="WorTitle" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-primary">Güncelle</button>
        <a asp-controller="Word" asp-action="Index" class="btn btn-secondary" style="width:150px">Geri Dön</a>
    </div>
</form>

Views/Word/Index.cshtml
@model IEnumerable<Word>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="col-6">
                Kelime Listesi
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Word" asp-action="Create" class="btn btn-primary">Ekle</a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Word 
            </th>
            <th>
                Word Title
            </th>
           
            
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.Wordname
                </td>
                <td>
                    @obj.WordTitle
                </td>
               
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Word" asp-action="Edit" asp-route-id="@obj.WordId" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Güncelle</a>
                    </div>
                </td>
                    <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Word" asp-action="Delete" asp-route-id="@obj.WordId" class="btn btn-danger mx-2"><i class="bi bi-trash3"></i>Sil</a>
                        </div>
                    </td>
            </tr>
        }
    </tbody>
</table>